apiVersion: v1
# 指的是k8s有哪些volume
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  # pvc文件要用的名字
  storageClassName: mysql-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  # 挂载目录
  hostPath:
    path: "/mnt/live"


  