// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go-study/webook/internal/repository"
	"go-study/webook/internal/repository/cache"
	"go-study/webook/internal/repository/dao"
	"go-study/webook/internal/service"
	"go-study/webook/internal/web"
	"go-study/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	codeCache := cache.NewCodeCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache, codeCache)
	emailService := ioc.InitEmailSms()
	tencentService := ioc.InitTencentSms()
	userServiceInterface := service.NewUserService(userRepository, emailService, tencentService)
	userHandler := web.NewUserHandler(userServiceInterface)
	engine := ioc.InitGin(v, userHandler)
	return engine
}
